### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by markib** [saqueib/qtube#2]
rand() expects exactly 2 parameters, 1 given

**Comment by saqueib** [comment]
you need to type range in this format `0-99`, start number and a `-` then end number.

one more thing, you need to have PHP v `5.6` or above, since I used `... (splat operator)`.

check the http://www.qcode.in/advance-interactive-database-seeding-in-laravel/ for more info.

**Comment by markib** [comment]
These credentials do not match our records.

**Comment by saqueib** [comment]
default password is `secret`, type this what have you tried.
